/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as MensageriaRouteImport } from './routes/mensageria.tsx'
import { Route as FeirasRouteImport } from './routes/feiras.tsx'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as IndexRouteImport } from './routes/index'

const MensageriaRoute = MensageriaRouteImport.update({
  id: '/mensageria',
  path: '/mensageria',
  getParentRoute: () => rootRouteImport,
} as any)
const FeirasRoute = FeirasRouteImport.update({
  id: '/feiras',
  path: '/feiras',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feiras': typeof FeirasRoute
  '/mensageria': typeof MensageriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feiras': typeof FeirasRoute
  '/mensageria': typeof MensageriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feiras': typeof FeirasRoute
  '/mensageria': typeof MensageriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/feiras' | '/mensageria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/feiras' | '/mensageria'
  id: '__root__' | '/' | '/dashboard' | '/feiras' | '/mensageria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FeirasRoute: typeof FeirasRoute
  MensageriaRoute: typeof MensageriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mensageria': {
      id: '/mensageria'
      path: '/mensageria'
      fullPath: '/mensageria'
      preLoaderRoute: typeof MensageriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feiras': {
      id: '/feiras'
      path: '/feiras'
      fullPath: '/feiras'
      preLoaderRoute: typeof FeirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FeirasRoute: FeirasRoute,
  MensageriaRoute: MensageriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
